<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Subscriptions PDF</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Arial, Helvetica, sans-serif;
            color: #6B6B6B;
            font-size: 14px;
            margin: 0;
        }
        h1, h2, h3, h4, h5, h6 {
            margin: 0;
            color: #010A0F;
            font-weight: 500;
        }
        p {
            margin: 0;
        }
        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }
        .header-logo {}
        .header-info {
            text-align: right;
            color: #010A0F;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            border: 1px solid #CCCCCC;
            margin-left: 0px;
        }
        thead {
            background-color: #F2F2F2;
        }
        th {
            color: #010A0F;
            font-weight: 600;
            padding: 4px;
            border: 1px solid #CCCCCC;
            text-align: left;
        }
        td {
            padding: 4px;
            border: 1px solid #CCCCCC;
            font-size: 12px;
        }
        tr:nth-child(even) td {
            background-color: #fafafa;
        }
        .footer {
            margin-top: 15px;
            text-align: right;
            font-size: 12px;
            color: #888;
        }
    </style>
</head>
<body>

<div class="header">
    <div class="header-logo">
        @include('frontend::components.partials.logo')
    </div>
    <div class="header-info">
        <p>{{ date('d M Y, h:i A') }}</p>
        <p><strong>Subscriptions List</strong></p>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>User Details</th>
            <th>Plan</th>
            <th>Duration</th>
            <th>Payment</th>
            <th>Start to End Date</th>
            <th>Amount</th>
            <th>Coupon</th>
            <th>Tax</th>
            <th>Total</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @forelse($data as $row)
            <tr>
                <td>{!! $row['user_details'] ?? '-' !!}</td>
                <td>{{ $row['name'] ?? '-' }}</td>
                <td>{{ $row['duration'] ?? '-' }}</td>
                <td>{{ $row['payment_method'] ?? '-' }}</td>
                <td>
                    @if(!empty($row['start_date']))
                        {{ \Carbon\Carbon::parse($row['start_date'])->format('d/m/Y') }}
                    @else
                        -
                    @endif
                    &nbsp;–&nbsp;
                    @if(!empty($row['end_date']))
                        {{ \Carbon\Carbon::parse($row['end_date'])->format('d/m/Y') }}
                    @else
                        -
                    @endif
                </td>
                <td>
                    @if(!empty($row['amount']))
                        {{ $row['amount'] }} BDT
                    @else
                        -
                    @endif
                </td>
                <td>{{ $row['coupon_discount'] ?? '-' }}</td>
                <td>{{ $row['tax_amount'] ?? '-' }}</td>
                <td>{{ $row['total_amount'] ?? '-' }}</td>
                <td>{{ ucfirst($row['status'] ?? '-') }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="11" style="text-align:center;">No data found</td>
            </tr>
        @endforelse
    </tbody>
</table>

<div class="footer">
    Generated by Z &mdash; {{ date('d M Y') }}
</div>

</body>
</html>
